### ISSUE TITLE
HTML templating?

### ISSUE THREAD

**Issue by ianpurton** [trezm/Thruster#103]
Will you be adding support for server side HTML generation?

For a full stack web framework the following would be required.

page generation
layouts
asset management i.e. webpack (for CSS, JS and images)

**Comment by trezm** [comment]
I'm not sure it's wise to make our own templating engine, since so many good ones already exist!

If you check out the intro at https://thruster.pete.pm, although parts still need to be updated for 0.7, there is a quick section on using Askama for templating.

In general though, thruster is an http framework for serving requests, it's concern isn't really to dictate how the frontend is structured or generated. That being said, it might be a fun project to add a "thruster-cli page <PageName>" command to the [thruster-cli](https://github.com/trezm/Thruster-cli)

For webpack and developing locally and allowing things like recompilation of your JS on save, I'd suggest a route that simply serves a file when running in development, but includes the resulting output in the binary when run in release. That way you get the best of both worlds!

**Comment by trezm** [comment]
Going to close this for lack of movement, although would be nice to have some middleware packages for this in the future!
