### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by CKarper** [trezm/Thruster#108]
Discussion issue for error handling in Thruster.

**Comment by CKarper** [comment]
The goal for me would be to be able to have middleware authors use `?` to escalate errors.  Allow registration of an error handler, or use a higher level middleware to handle errors.

The current difficulty is the ownership chain of `Context` in middlewares.  Since ownership is given in each `next` call, and then returned, any switch to an `Error` in a `Result` loses the context.   Which means losing the `Request` information as well as the `Response` so far.

That makes it more difficult to format an error body that depends on the client `Accept` header.

Either creation of an `Error` that can capture the current `Context`, or a change to the ownership model of `Context` would make error handling more palatable.  Both approaches have difficulties and drawbacks.

**Comment by kjvalencik** [comment]
I'm not sure if this would work and it would be a massive breaking change, but what if the server owned the context rather than threading ownership through the middleware? This could be coupled with middleware being generic of an `Error` type. It could allow returning custom errors and handling them in other pieces of middleware (similar to koa).

A mocked middleware signature:
```rust
async fn middleware<C, E>(context: &mut C, next: MiddlewareNext<C>) -> Result<(), E> where C: Context, E: ThrusterError;
```

Errors would need to implement `ThrusterError` would provides a single method for converting an unhandled error to a response.

**Comment by trezm** [comment]
Dealing with lifetimes within the middleware chain has proven to be a bear over time because of the static implications of futures unfortunately. That being said, I could be approaching the problem incorrectly, so if someone is able to implement it more power to them!

What I'm trying to implement is somewhat similar currently, the signature of which will look like this:
```rust
async fn middleware(context: Context, next: MiddlewareNext<Context>) -> Result<Context, ThrusterError<Context>>
```

`ThrusterError<T>` will be able to, when fed a context, properly update the body and status to reflect the error.

**Comment by CKarper** [comment]
That seems like a fairly reasonable approach.  If there is trouble moving the `Context` into the `ThrusterError`, it could live with just the `Request`.

**Comment by trezm** [comment]
I was thinking the former, and adding `set_status` as a requirement for contexts, but am open to either solution.

**Comment by CKarper** [comment]
I like the idea of handling the error myself when wanted.   I may want to deal with it as part of a graphql query, for instance...   Or I could decide whether to show a formatted HTML doc, vs. JSON error structure.

I think having the Error handle a fallback where none of that was done would make sense.

**Comment by trezm** [comment]
Let me think on the least disruptive way to accomplish this, might take some refactoring :)

**Comment by CKarper** [comment]
Happy to help however I can.  I'm new, but tenacious.

**Comment by CKarper** [comment]
I didn't even compile this, but, as a thought...
```rust
pub type ThrusterResult<T> = Result<T, ThrusterError<T>>;

pub fn init() -> App<Request, Ctx> {
    let mut app = App::<Request, Ctx>::new_basic();

    app.use_middleware("", async_middleware!(Ctx, [errors, all_requests]));
    app.get("/dangerous", async_middleware!(Ctx, [be_dangerous]));

    app
}
```

Error starts in `be_dangerous`, in `all_requests` the escalated via the `.await?`.
It's finally handled in `errors` middleware.  

```rust
#[middleware_fn]
pub async fn be_dangerous(context: Ctx, next: MiddlewareNext<Ctx>) -> ThrusterResult<Ctx> {
    Err("I did something bad")
}

#[middleware_fn]
pub async fn all_requests(context: Ctx, next: MiddlewareNext<Ctx>) -> ThrusterResult<Ctx> {
    let start_time = Instant::now();

    // let mut needed because rust-lang/rust#60674
    let mut context = next(context).await?;

    context.set("Server", crate::SERVER_VERSION);

    let elapsed_time = start_time.elapsed();
    println!(
        "{} {} {} ({}μs)",
        context.status,
        context.request.method(),
        context.request.path(),
        elapsed_time.as_micros()
    );

    Ok(context)
}

#[middleware_fn]
pub async fn errors(context: Ctx, next: MiddlewareNext<Ctx>) -> ThrusterResult<Ctx> {
    next(context).await.unwrap_or_else(|e| {
        e.context.body(e.to_string().clone());
        e.context.status(500);

        Ok(e.context)
    })
}
```

If the error propagates all the way out to `Thruster` after this last middleware, then a default error format would be ideal.

**Comment by trezm** [comment]
Yes, I like this format of how the errors bubble up!!

The question that I've been running into locally is where does that `e.context` come from? Passing ownership is not an option in something like this:

```
  let non_existent_param = "Hello, world".parse::<u32>()
    .map_err(|_| Error::new(context, "parse error!"))?;

  context.body(&format!("{}", non_existent_param));

  Ok(context)
```

Gives an ownership error since `context` is moved when the new error is created, but then used again when the body is set (even though those two paths don't exist simultaneously in this case.)

**Comment by CKarper** [comment]
Can you clone it in case of an error?

**Comment by trezm** [comment]
Going to try to investigate moving contexts to a moveable borrow as
suggested earlier (again.) If that doesn't pan out, I think we'll have to,
or encourage new contexts for error creation.

**Comment by kjvalencik** [comment]
Thanks @trezm. Borrowed contexts seems like the most ergonomic solution--if it works--but, I wanted to share how I'm currently handling errors. It's not ideal, but might inform some better ideas.

## Custom context enum

One variant for success and one for failure. `std::ops::Try` is implemented for it to allow `?`.

```rs
pub struct ErrorContext {
	cause: Error,
	response: Response,
}

pub enum Ctx {
	Ok(BasicContext),
	Err(ErrorContext),
}

impl Ctx {
	pub fn generate(request: Request) -> Self {
		use thruster::thruster_context::basic_context;

		let ctx = basic_context::generate_context(request);

		Ctx::Ok(ctx)
	}
}

impl std::ops::Try for Ctx {
	type Ok = BasicContext;
	type Error = ErrorContext;

	fn into_result(self) -> Result<BasicContext, ErrorContext> {
		match self {
			Ctx::Ok(v) => Ok(v),
			Ctx::Err(v) => Err(v),
		}
	}

	fn from_ok(v: BasicContext) -> Self {
		Ctx::Ok(v)
	}

	fn from_error(v: ErrorContext) -> Self {
		Ctx::Err(v)
	}
}
```

## Error enum

Errors are mapped into a `failure` enum and a `ResultExt` trait is provided for adding context to errors within middleware.

```
pub trait ResultExt<T> {
	fn err_context(
		self,
		ctx: &BasicContext,
		status: StatusCode,
		context: &str,
	) -> ResultContext<T>;
}
```

## Usage

Middleware usage requires unwrapping context (`let mut ctx = ctx?;`).

```rs
#[middleware_fn]
pub async fn middleware(ctx: Ctx, _next: MiddlewareNext<Ctx>) -> Ctx {
	let mut ctx = ctx?;
	let fr: api::FulfillmentRequest =
		ctx.request.body_as(ctx.request.body()).err_context(
			&ctx,
			StatusCode::BAD_REQUEST,
			"Failed to deserialize request body",
		)?;
```

Outside of borrowed contexts, there are a couple of things that could clean this up. If user defined errors (implementing `trait ThrusterError`) could be returned from middleware, the strange context mapping and `Try` implementation wouldn't be necessary. If `context` and `request` implemented `Clone`, then it could be cloned in the uncommon `error` path, allowing for future access.

**Comment by trezm** [comment]
This workaround is fascinating -- so all of your middleware essentially returns this enum, but am I right in thinking that the enum doesn't implement the `Context` trait, or did you leave that out of the code above for brevity?

If not, can you post a quick complete example, because I've been staring at the actual thruster lib code and have questions as to why this works :)

In other news -- still looking into borrowing contexts instead of moving them, but your solution of implementing `Try` for context is really intriguing and I have to look into it further, thanks so much for posting the example!!!

**Comment by kjvalencik** [comment]
Yes, I omitted the impl for Context. I'll share a more complete example when I'm at my laptop.

**Comment by CKarper** [comment]
![](https://giphy.com/gifs/smart-good-will-hunting-4Bvpcq8rj4PmM)

**Comment by trezm** [comment]
Delivered as of #110
