### ISSUE TITLE
file content example 

### ISSUE THREAD

**Issue by ami44** [trezm/Thruster#72]
thank you for BasicContext update (and cookie). very great. 
I search a minimal middleware example for return file content (image, favicon. ..) async example with tokio' not a sync example.
thanks
ami44

**Comment by jacobbudin** [comment]
For what it's worth to future PR creators, I've explored adding file responses and it's not trivial.  [`Context::set_body`](https://github.com/trezm/Thruster/blob/40f9e78e9512b96612d5c4e4794540dde84b1706/src/context.rs#L9) takes the response body as a `String`. Since Rust requires `String`s to be valid UTF-8, there's no good way to set the body to a file's contents (`Vec<u8>` presumably).

Regardless, you can instead create your own implementation of `Context`, but since `Context`  isn't public, you'll need to add something like `ByteContext` to the library source. Then there's the matter of implementing `set_body`. You could leave `set_body` as `unimplemented!`, but that seems rude.

Apologies for any inaccuracies. I'm new to the library.

**Comment by trezm** [comment]
That's a valid point -- realistically `set_body` should take a `Vec<u8>` and specific implementors should implement their own `set_body_as_string` or something like that. I'll change/implement that in the near future!

Just a note, `Context` _is_ actually [public](https://github.com/trezm/Thruster/blob/master/src/lib.rs#L39), but the point about its use within thruster is understood, so I agree, let's change `Context::set_body` to take a `Vec<u8>`.

**Comment by ami44** [comment]
Thank you
