### ISSUE TITLE
Allow use of different contexts in sub apps

### ISSUE THREAD

**Issue by NeoLegends** [trezm/Thruster#84]
I was wondering why it isn‘t possible to use a different type of context in the sub apps. I haven‘t done much work with this library yet but this seems to hinder usability, does it? I can imagine a scenario where I‘d have an /api endpoint that automatically parses all requests as JSON (and stores the data on the context) while the other endpoints would treat the requests differently.

**Comment by trezm** [comment]
Just to update some progress, or lack thereof, that I've made:

- Supporting this appears to be a big task because of how the app resolution trees are merged together. An app's routes are currently stored as a tree, where each node has a `SmallVec<Middleware<T>>` of middleware functions. Since we can only reference impl traits in function signatures, we can't simply change this into `SmallVec<Middleware<impl Into<T>>`.
- I investigated attempting to curry middleware chains when adding a subapp, but this also won't work because of the discrepancy between closures and fn pointers, and we'd need a capturing closure in order make the conversion correctly.

I see the benefit of having apps be totally separable from each other, but I think it'll require a decent refactor to get to that point. Until then, here's a "half way there" solution that might be of interest:

```rust
extern crate thruster;
extern crate futures;

use futures::future;

use thruster::{App, BasicContext, Context, MiddlewareChain, MiddlewareReturnValue};
use thruster::builtins::server::Server;
use thruster::builtins::basic_context::generate_context;
use thruster::server::ThrusterServer;

trait Ctx1 {
  fn set_hello_world(&mut self);
}

trait Ctx2 {
  fn set_goodbye_world(&mut self);
}

impl Ctx1 for BasicContext {
  fn set_hello_world(&mut self) {
    self.body = "Hello, World!".to_owned();
  }
}

impl Ctx2 for BasicContext {
  fn set_goodbye_world(&mut self) {
    self.body = "Goodbye, cruel world!".to_owned();
  }
}

fn hello<Ctx: 'static + Ctx1 + Context + Send>(mut context: Ctx, _chain: &MiddlewareChain<Ctx>) -> MiddlewareReturnValue<Ctx> {
  context.set_hello_world();

  Box::new(future::ok(context))
}

fn goodbye<Ctx: 'static + Ctx2 + Context + Send>(mut context: Ctx, _chain: &MiddlewareChain<Ctx>) -> MiddlewareReturnValue<Ctx> {
  context.set_goodbye_world();

  Box::new(future::ok(context))
}

fn main() {
  println!("Starting server...");

  let mut app = App::create(generate_context);
  let mut sub_app = App::create(generate_context);

  sub_app.get("/", vec![goodbye]);

  app.get("/hello", vec![hello]);
  app.use_sub_app("/goodbye", sub_app);

  let server = Server::new(app);
  server.start("0.0.0.0", 4321);
}
```

The idea being that, yes, your context struct itself would be messy, but you'd provide access to individual pieces of it via traits, so, in that way, you could simplify the interface for sub apps.

I'll keep working/thinking on a valid solution for composing different contexts in the mean time!

**Comment by trezm** [comment]
Hey, @NeoLegends, I finally was able to figure out a good way of doing multicontext! Check out https://github.com/trezm/Thruster/blob/master/examples/multicontext.rs for an example on how it works.

The TLDR; As long as one of the contexts implements `From` and `Into` the other context, you can use whichever context you'd like.
